Add check of swift downloading
Change-Id: Ic7049f914a5917a71546552b7108a576a8588a93

diff --git a/elements/swift_hadoop/post-install.d/81-add-jar b/elements/swift_hadoop/post-install.d/81-add-jar
--- a/elements/swift_hadoop/post-install.d/81-add-jar
+++ b/elements/swift_hadoop/post-install.d/81-add-jar
@@ -4,4 +4,8 @@ if [ -z "$swift_url" ]; then
 else
    wget -O /usr/share/hadoop/lib/hadoop-swift.jar $swift_url
 fi
+if [ $? -ne 0 ]; then
+   echo -e "Could not download Swift Hadoop FS implementation.\nAborting"
+   exit 1
+fi
 chmod 0644 /usr/share/hadoop/lib/hadoop-swift.jar
