Fix a removed variable, properly check the Hadoop version
With the introduction of support for 2.3 and 2.4 the variable
HADOOP_V2_NATIVE_LIBS_DOWNLOAD_URL has been split into
the HADOOP_V2_3_... and HADOOP_V2_4_... variant; this part
of the code needs to be updated as well, otherwise the
installation of native libs fails.

In addition, properly fail if the requested Hadoop version
does not match a know one.

Change-Id: If05afc90a5f081030f7efa449f8bae5b7565a74e

diff --git a/elements/hadoop/post-install.d/40-setup-hadoop b/elements/hadoop/post-install.d/40-setup-hadoop
--- a/elements/hadoop/post-install.d/40-setup-hadoop
+++ b/elements/hadoop/post-install.d/40-setup-hadoop
@@ -83,6 +83,19 @@ EOF
 
 function install_hadoop_v2()
 {
+    case "$DIB_HADOOP_VERSION" in
+        "2.3.0")
+             hadoop_native_libs_url="${HADOOP_V2_3_NATIVE_LIBS_DOWNLOAD_URL}"
+        ;;
+        "2.4.1")
+             hadoop_native_libs_url="${HADOOP_V2_4_NATIVE_LIBS_DOWNLOAD_URL}"
+        ;;
+        *)
+             echo "Invalid DIB_HADOOP_VERSION: $DIB_HADOOP_VERSION"
+             exit 1
+        ;;
+    esac
+
     package="hadoop-$DIB_HADOOP_VERSION.tar.gz"
 
     download_hadoop_package
@@ -100,8 +113,8 @@ function install_hadoop_v2()
 
     echo "Inject Hadoop native libs"
     rm -r "$HADOOP_HOME/lib/native"
-    wget "$HADOOP_V2_NATIVE_LIBS_DOWNLOAD_URL"
-    native_libs_filename=$(basename "$HADOOP_V2_NATIVE_LIBS_DOWNLOAD_URL")
+    wget "$hadoop_native_libs_url"
+    native_libs_filename=$(basename "$hadoop_native_libs_url")
     tar xvf "$native_libs_filename" -C "$HADOOP_HOME/lib"
     rm "$native_libs_filename"
 
