Revise s3_hadoop
* Handle Hadoop classpath better
* Include proper support for Spark classpath
* Formally limit element's use to Vanilla and Spark

Change-Id: I65abd7e375dba11599a4ab943d24f878235cd71d
Closes-Bug: #1727757
Closes-Bug: #1728061

diff --git a/elements/s3_hadoop/post-install.d/89-add-amazon-jar b/elements/s3_hadoop/post-install.d/89-add-amazon-jar
--- a/elements/s3_hadoop/post-install.d/89-add-amazon-jar
+++ b/elements/s3_hadoop/post-install.d/89-add-amazon-jar
@@ -5,32 +5,56 @@ fi
 set -eu
 set -o pipefail
 
-if [ -z "${HADOOP_S3_JAR_ORIGIN:-}" ]; then
-    # The jar is not locally available during image-gen on Ambari/MapR plugins: relevant packages are installed later.
-    # The jar is not appropriate for the Storm plugin: you cannot stream data from an object store.
-    # For plugins not found in the switch statement below, a user-specified jar can still be downloaded.
-    case "$plugin_type" in
-        "vanilla")
-            HADOOP_S3_JAR_ORIGIN="/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-$DIB_HADOOP_VERSION.jar"
-            ;;
-        "cloudera" | "spark" )
-            HADOOP_S3_JAR_ORIGIN="/usr/lib/hadoop/hadoop-aws.jar"
-            ;;
-    esac
-fi
 
-HDFS_LIB_DIR=${DIB_HDFS_LIB_DIR:-"/usr/share/hadoop/lib"} # matches swift_hadoop default
+case "$plugin_type" in
+    "vanilla" )
+        HADOOP_TOOLS_DIR_PATH="/opt/hadoop/share/hadoop/tools/lib"
+        HADOOP_ENV_SH_PATH="/opt/hadoop/etc/hadoop/hadoop-env.sh"
+        SPARK_JARS_DIR_PATH="/opt/spark/jars"
+        ;;
+    "spark" )
+        HADOOP_TOOLS_DIR_PATH="/usr/lib/hadoop/client"
+        SPARK_JARS_DIR_PATH="/opt/spark/jars"
+        ;;
+    "cloudera" )
+        echo -n "The s3_hadoop element is not supported on CDH,"
+        echo " because the relevant libraries are already in the right place."
+        exit 1
+        ;;
+    *)
+        echo "The s3_hadoop element is only supported on Vanilla and Spark."
+        exit 1
+esac
 
-if [ -z "${HADOOP_S3_JAR_DOWNLOAD:-}" ]; then
-    if [ "${HADOOP_S3_JAR_ORIGIN:-}" ]; then
-        cp $HADOOP_S3_JAR_ORIGIN $HDFS_LIB_DIR/hadoop-aws.jar
+# NOTE: By defintion, the Spark standalone plugin does not contain Hadoop in
+# its entirety. Therefore, there are no Hadoop-specific environment settings
+# available for modification.
+if [ "$plugin_type" != "spark" ]; then
+    if [ -f "$HADOOP_ENV_SH_PATH" ]; then
+        cat >> $HADOOP_ENV_SH_PATH <<EOF
+for f in $HADOOP_TOOLS_DIR_PATH/*.jar; do
+    if [ "\$HADOOP_CLASSPATH" ]; then
+        export HADOOP_CLASSPATH=\$HADOOP_CLASSPATH:\$f
+    else
+        export HADOOP_CLASSPATH=\$f
     fi
-else
-    wget -O $HDFS_LIB_DIR/hadoop-aws.jar $HADOOP_S3_JAR_DOWNLOAD
+done
+EOF
+    else
+        echo "Something went wrong: couldn't find Hadoop env settings."
+        exit 1
+    fi
 fi
 
-path=$HDFS_LIB_DIR/hadoop-aws.jar
-
-if [ -f $path ]; then
-    chmod 0644 $path
+if [ -d "$SPARK_JARS_DIR_PATH" ]; then
+    cp $HADOOP_TOOLS_DIR_PATH/*aws*.jar $SPARK_JARS_DIR_PATH
+    chmod 0644 $SPARK_JARS_DIR_PATH/*aws*jar
+else
+    # NOTE: In the case of Vanilla, the user may have disabled the Spark
+    # element. So, check for the existence of the directory explicitly, but
+    # crucially do do not consider it an error if the folder does not exist.
+    if [ "$plugin_type" != "vanilla" ]; then
+        echo "Something went wrong: couldn't find Spark installation."
+        exit 1
+    fi
 fi
