Setup password for root using variable 'DIB_PASSWORD'
Move ssh configuration for root login into 'root-passwd' element.

Fixes: bug #1199970

Change-Id: Iaac460394482651d8cb3d73dd924fcb600d3065c

diff --git a/elements/root-passwd/post-install.d/99-setup b/elements/root-passwd/post-install.d/99-setup
--- a/elements/root-passwd/post-install.d/99-setup
+++ b/elements/root-passwd/post-install.d/99-setup
@@ -1,4 +1,11 @@
 #!/bin/bash
-echo "Setting up root password"
-echo -e "swordfish\nswordfish\n" | passwd
-
+if [ -z "$DIB_PASSWORD" ]; then
+   echo "Error during setup password for root"
+   exit 1
+fi
+sed -i "s/disable_root: true/disable_root: false/" /etc/cloud/cloud.cfg
+install-packages augeas-tools openssh-server openssh-client
+augtool -s set /files/etc/ssh/sshd_config/PasswordAuthentication yes
+augtool -s set /files/etc/ssh/sshd_config/PermitRootLogin yes
+augtool -s set /files/etc/ssh/ssh_config/PasswordAuthentication yes
+echo -e "$DIB_PASSWORD\n$DIB_PASSWORD\n" | passwd
