Simplification of hadoop_fedora/11-setup-java implementation
Change-Id: If6a9f6a577fd5cf8426aa86a0155610d7e96dde5

diff --git a/elements/hadoop_fedora/post-install.d/11-setup-java b/elements/hadoop_fedora/post-install.d/11-setup-java
--- a/elements/hadoop_fedora/post-install.d/11-setup-java
+++ b/elements/hadoop_fedora/post-install.d/11-setup-java
@@ -1,44 +1,34 @@
 #!/bin/bash
 echo "Java setup begins"
-install-packages wget
-tmp_dir=/tmp/java/
-mkdir -p $TARGET_ROOT/$tmp_dir
 set -e
-if [ -z "$JAVA_DOWNLOAD_URL" ]; then
-   script_dir=$(dirname $0)
-   install -D -g root -o root -m 0755 $script_dir/$JAVA_FILE $TARGET_ROOT/$tmp_dir
-   filename=$JAVA_FILE
-   echo "Java file moved"
-else
-   wget --no-cookies --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com" -P $TARGET_ROOT/$tmp_dir $JAVA_DOWNLOAD_URL
+
+# NOTE: $(dirname $0) is read-only, use space under $TARGET_ROOT
+JAVA_HOME=$TARGET_ROOT/usr/java
+mkdir -p $JAVA_HOME
+
+if [ -n "$JAVA_DOWNLOAD_URL" ]; then
+   install-packages wget
+   wget --no-cookies --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com" -P $JAVA_HOME $JAVA_DOWNLOAD_URL
    if [ $? -eq 0 ]; then
-      echo "Java is downloading"
-      else
-      echo "Url error. Exit"
+      echo "Java downloaded"
+   else
+      echo "Error downloading java. Exiting."
       exit 1
    fi
-   filename=$(find $TARGET_ROOT/$tmp_dir -maxdepth 1 -name "jdk*")
-   filename=$(basename $filename)
+   JAVA_FILE=$(basename $JAVA_DOWNLOAD_URL)
+elif [ -n "$JAVA_FILE" ]; then
+   install -D -g root -o root -m 0755 $(dirname $0)/$JAVA_FILE $JAVA_HOME
 fi
 
-if echo $tmp_dir/$filename | grep -q -s -F .tar.gz ; then
-   pushd $TARGET_ROOT/$tmp_dir
-   echo -e "\n" | tar -zxvf $TARGET_ROOT/$tmp_dir/$filename
-   popd
-   else
-      if echo $filename | grep -q -s -F .bin ; then
-         pushd $TARGET_ROOT/$tmp_dir
-         echo -e "\n" | sh $filename
-         rm $filename
-         popd
-      fi
+cd $JAVA_HOME
+if echo $JAVA_FILE | grep -q -s -F .tar.gz ; then
+   echo -e "\n" | tar -zxvf $JAVA_FILE
+elif echo $JAVA_FILE | grep -q -s -F .bin ; then
+   echo -e "\n" | sh $JAVA_FILE
+else
+   echo "Unknown file type: $JAVA_FILE. Exiting."
+   exit 1
 fi
+rm $JAVA_FILE
 
-filename=$(find $TARGET_ROOT/$tmp_dir -maxdepth 1 -type d -name "jdk*")
-filename=$(basename $filename)
-javaPath=/usr/java/
-mkdir -p $TARGET_ROOT/$javaPath
-mv $TARGET_ROOT/$tmp_dir/$filename $TARGET_ROOT/$javaPath
-rm -r $tmp_dir
 echo "Java was installed"
-
