Fix bashate errors
Change-Id: Icee255fc3393bad79ca02457395170af42c61a32

diff --git a/elements/hadoop-cdh/post-install.d/40-setup-hadoop b/elements/hadoop-cdh/post-install.d/40-setup-hadoop
--- a/elements/hadoop-cdh/post-install.d/40-setup-hadoop
+++ b/elements/hadoop-cdh/post-install.d/40-setup-hadoop
@@ -6,8 +6,8 @@
 
 distro=$(lsb_release -is || :)
 if [ "$distro" != "Ubuntu" ]; then
-   echo "Distro $distro not supported by CDH. Exiting."
-   exit 1
+    echo "Distro $distro not supported by CDH. Exiting."
+    exit 1
 fi
 
 echo "Hadoop CDH setup begins for $distro"
@@ -15,11 +15,11 @@ tmp_dir=/tmp/hadoop
 
 echo "Creating hadoop user & group"
 case "$distro" in
-   Ubuntu )
-      addgroup hadoop
-      adduser --ingroup hadoop --disabled-password --gecos GECOS hadoop
-      adduser hadoop sudo
-   ;;
+    Ubuntu )
+        addgroup hadoop
+        adduser --ingroup hadoop --disabled-password --gecos GECOS hadoop
+        adduser hadoop sudo
+    ;;
 esac
 
 echo "CDH 4 will be injected into image. Starting the download"
@@ -28,8 +28,8 @@ install-packages wget
 # Here more versions of CDH could be supported by downloading the right repository package.
 wget -P $tmp_dir "http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb"
 if [ $? -ne 0 ]; then
-   echo -e "Could not find CDH 4.\nAborting"
-   exit 1
+    echo -e "Could not find CDH 4.\nAborting"
+    exit 1
 fi
 
 # Pin packages from cloudera repository
@@ -40,13 +40,13 @@ Pin-Priority: 800
 EOF
 
 case "$distro" in
-   Ubuntu )
-      dpkg -i $tmp_dir/cdh4-repository_1.0_all.deb
-      curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -
-      sudo apt-get update
-      # Here the script could be expanded to install all CDH packages and not only HDFS.
-      install-packages hadoop-hdfs-namenode hadoop-hdfs-datanode
-   ;;
+    Ubuntu )
+        dpkg -i $tmp_dir/cdh4-repository_1.0_all.deb
+        curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -
+        sudo apt-get update
+        # Here the script could be expanded to install all CDH packages and not only HDFS.
+        install-packages hadoop-hdfs-namenode hadoop-hdfs-datanode
+    ;;
 esac
 rm -r $tmp_dir
 
@@ -57,11 +57,11 @@ echo "Pre-configuring Hadoop"
 JAVA_HOME=$(find $TARGET_ROOT$JAVA_TARGET_LOCATION/ -maxdepth 1 -name "jdk*")
 
 if [ -z "$JAVA_HOME" ]; then
-   case "$distro" in
-      Ubuntu)
-         JAVA_HOME=$(readlink -e /usr/bin/java | sed "s:bin/java::")
-      ;;
-   esac
+    case "$distro" in
+        Ubuntu)
+            JAVA_HOME=$(readlink -e /usr/bin/java | sed "s:bin/java::")
+        ;;
+    esac
 fi
 
 cat >> /home/hadoop/.bashrc <<EOF
diff --git a/elements/hadoop/post-install.d/40-setup-hadoop b/elements/hadoop/post-install.d/40-setup-hadoop
--- a/elements/hadoop/post-install.d/40-setup-hadoop
+++ b/elements/hadoop/post-install.d/40-setup-hadoop
@@ -7,8 +7,7 @@
 # HADOOP-9777 is resolved.
 #   https://issues.apache.org/jira/browse/HADOOP-9777
 
-function download_hadoop_package()
-{
+function download_hadoop_package {
     echo "Hadoop version $DIB_HADOOP_VERSION will be injected into image. Starting the download"
     install-packages wget
     wget -P $tmp_dir "http://archive.apache.org/dist/hadoop/core/hadoop-$DIB_HADOOP_VERSION/$package"
@@ -18,8 +17,7 @@ function download_hadoop_package()
     fi
 }
 
-function find_java_home()
-{
+function find_java_home {
     JAVA_HOME=$(find $TARGET_ROOT$JAVA_TARGET_LOCATION/ -maxdepth 1 -name "jdk*")
 
     if [ -z "$JAVA_HOME" ]; then
@@ -34,8 +32,7 @@ function find_java_home()
     fi
 }
 
-function install_hadoop_v1()
-{
+function install_hadoop_v1 {
     case "$distro" in
         Ubuntu )
             package="hadoop_$DIB_HADOOP_VERSION-1_x86_64.deb"
@@ -75,24 +72,23 @@ HADOOP_HOME=/usr/share/hadoop/
 EOF
 
     sed -i -e "s,export JAVA_HOME=.*,export JAVA_HOME=$JAVA_HOME," \
-           -e "s,export HADOOP_LOG_DIR=.*,export HADOOP_LOG_DIR=/mnt/log/hadoop/\$USER," \
-           -e "s,export HADOOP_SECURE_DN_LOG_DIR=.*,export HADOOP_SECURE_DN_LOG_DIR=/mnt/log/hadoop/hdfs," \
+        -e "s,export HADOOP_LOG_DIR=.*,export HADOOP_LOG_DIR=/mnt/log/hadoop/\$USER," \
+        -e "s,export HADOOP_SECURE_DN_LOG_DIR=.*,export HADOOP_SECURE_DN_LOG_DIR=/mnt/log/hadoop/hdfs," \
         /etc/hadoop/hadoop-env.sh
 }
 
 
-function install_hadoop_v2()
-{
+function install_hadoop_v2 {
     case "$DIB_HADOOP_VERSION" in
         "2.3.0")
-             hadoop_native_libs_url="${HADOOP_V2_3_NATIVE_LIBS_DOWNLOAD_URL}"
+            hadoop_native_libs_url="${HADOOP_V2_3_NATIVE_LIBS_DOWNLOAD_URL}"
         ;;
         "2.4.1")
-             hadoop_native_libs_url="${HADOOP_V2_4_NATIVE_LIBS_DOWNLOAD_URL}"
+            hadoop_native_libs_url="${HADOOP_V2_4_NATIVE_LIBS_DOWNLOAD_URL}"
         ;;
         *)
-             echo "Invalid DIB_HADOOP_VERSION: $DIB_HADOOP_VERSION"
-             exit 1
+            echo "Invalid DIB_HADOOP_VERSION: $DIB_HADOOP_VERSION"
+            exit 1
         ;;
     esac
 
@@ -131,12 +127,12 @@ export HADOOP_MAPRED_HOME=\$HADOOP_COMMON_HOME
 EOF
 
     sed -i -e "s,export JAVA_HOME=.*,export JAVA_HOME=$JAVA_HOME," \
-           -e "s,\#export HADOOP_LOG_DIR=.*,export HADOOP_LOG_DIR=/mnt/log/hadoop/\$USER," \
-           -e "s,export HADOOP_SECURE_DN_LOG_DIR=.*,export HADOOP_SECURE_DN_LOG_DIR=/mnt/log/hadoop/hdfs," \
+        -e "s,\#export HADOOP_LOG_DIR=.*,export HADOOP_LOG_DIR=/mnt/log/hadoop/\$USER," \
+        -e "s,export HADOOP_SECURE_DN_LOG_DIR=.*,export HADOOP_SECURE_DN_LOG_DIR=/mnt/log/hadoop/hdfs," \
         $HADOOP_HOME/etc/hadoop/hadoop-env.sh
 
     sed -i -e "s,\# export JAVA_HOME=.*,export JAVA_HOME=$JAVA_HOME," \
-           -e "s,YARN_LOG_DIR=.*,YARN_LOG_DIR=/mnt/log/hadoop/yarn," \
+        -e "s,YARN_LOG_DIR=.*,YARN_LOG_DIR=/mnt/log/hadoop/yarn," \
         $HADOOP_HOME/etc/hadoop/yarn-env.sh
 
     # enable swiftfs
@@ -145,8 +141,8 @@ EOF
 
 distro=$(lsb_release -is || :)
 if [ ! "$distro" == "Fedora" -a ! "$distro" == "Ubuntu" -a ! "$distro" == "RedHatEnterpriseServer" -a ! "$distro" == "CentOS" ]; then
-   echo "Unknown distro: $distro. Exiting."
-   exit 1
+    echo "Unknown distro: $distro. Exiting."
+    exit 1
 fi
 
 echo "Hadoop setup begins for $distro"
@@ -154,14 +150,14 @@ tmp_dir=/tmp/hadoop
 
 echo "Creating hadoop user & group"
 case "$distro" in
-   Ubuntu )
-      addgroup hadoop
-      adduser --ingroup hadoop --disabled-password --gecos GECOS hadoop
-      adduser hadoop sudo
-   ;;
-   Fedora | RedHatEnterpriseServer | CentOS )
-      adduser -G adm,wheel hadoop
-   ;;
+    Ubuntu )
+        addgroup hadoop
+        adduser --ingroup hadoop --disabled-password --gecos GECOS hadoop
+        adduser hadoop sudo
+    ;;
+    Fedora | RedHatEnterpriseServer | CentOS )
+        adduser -G adm,wheel hadoop
+    ;;
 esac
 
 : ${JAVA_TARGET_LOCATION:="/usr/java"}
@@ -176,17 +172,17 @@ echo "Applying firstboot script"
 
 RC_SCRIPT_DIR=""
 if [ "$distro" == "Ubuntu" ]; then
-  # File '/etc/rc.local' may not exist
-  if [ -f "/etc/rc.local" ]; then
-    mv /etc/rc.local /etc/rc.local.old
-  fi
-  RC_SCRIPT_DIR="/etc"
+    # File '/etc/rc.local' may not exist
+    if [ -f "/etc/rc.local" ]; then
+        mv /etc/rc.local /etc/rc.local.old
+    fi
+    RC_SCRIPT_DIR="/etc"
 else
-  # File '/etc/rc.d/rc.local' may not exist
-  if [ -f "/etc/rc.d/rc.local" ]; then
-    mv /etc/rc.d/rc.local /etc/rc.d/rc.local.old
-  fi
-  RC_SCRIPT_DIR="/etc/rc.d"
+    # File '/etc/rc.d/rc.local' may not exist
+    if [ -f "/etc/rc.d/rc.local" ]; then
+        mv /etc/rc.d/rc.local /etc/rc.d/rc.local.old
+    fi
+    RC_SCRIPT_DIR="/etc/rc.d"
 fi
 
 install -D -g root -o root -m 0755 $(dirname $0)/firstboot $RC_SCRIPT_DIR/rc.local
diff --git a/elements/hadoop/root.d/0-check b/elements/hadoop/root.d/0-check
--- a/elements/hadoop/root.d/0-check
+++ b/elements/hadoop/root.d/0-check
@@ -2,18 +2,18 @@
 set -e
 
 if [ -z "$JAVA_DOWNLOAD_URL" ]; then
-   if [ -z "$JAVA_FILE" ]; then
-      echo "JAVA_FILE and JAVA_DOWNLOAD_URL are not set. Proceeding with distro native Java."
-   fi
+    if [ -z "$JAVA_FILE" ]; then
+        echo "JAVA_FILE and JAVA_DOWNLOAD_URL are not set. Proceeding with distro native Java."
+    fi
 fi
 if [ -z "$DIB_HADOOP_VERSION" ]; then
-   echo "DIB_HADOOP_VERSION is not set. Impossible to install hadoop. Exit"
-   exit 1
+    echo "DIB_HADOOP_VERSION is not set. Impossible to install hadoop. Exit"
+    exit 1
 fi
 version_check=$(echo $DIB_HADOOP_VERSION | sed -e '/[0-9]\.[0-9]\.[0-9]/d')
 if [[ -z $version_check ]]; then
-   echo "All variables are set, continue."
+    echo "All variables are set, continue."
 else
-   echo "Version error. Exit"
-   exit 1
+    echo "Version error. Exit"
+    exit 1
 fi
diff --git a/elements/hive/post-install.d/60-hive b/elements/hive/post-install.d/60-hive
--- a/elements/hive/post-install.d/60-hive
+++ b/elements/hive/post-install.d/60-hive
@@ -6,12 +6,12 @@ mkdir -p $tmp_dir
 cd $tmp_dir
 
 if [ -z $HIVE_DOWNLOAD_URL ]; then
-  HIVE_DOWNLOAD_URL=http://archive.apache.org/dist/hive/hive-$HIVE_VERSION/hive-$HIVE_VERSION-bin.tar.gz
+    HIVE_DOWNLOAD_URL=http://archive.apache.org/dist/hive/hive-$HIVE_VERSION/hive-$HIVE_VERSION-bin.tar.gz
 fi
 wget $HIVE_DOWNLOAD_URL
 if [ $? -ne 0 ]; then
-   echo -e "Could not download hive.\nAborting"
-   exit 1
+    echo -e "Could not download hive.\nAborting"
+    exit 1
 fi
 HIVE_FILE=$(basename $HIVE_DOWNLOAD_URL)
 tar xzf $HIVE_FILE
diff --git a/elements/hive/root.d/0-check b/elements/hive/root.d/0-check
--- a/elements/hive/root.d/0-check
+++ b/elements/hive/root.d/0-check
@@ -1,8 +1,8 @@
 #!/bin/bash
 if [ -z "$HIVE_DOWNLOAD_URL" ]; then
-  version_check=$(echo $HIVE_VERSION | sed -e '/[0-9]\.[0-9][0-9]\.[0-9]/d')
-  if [ ! -z $version_check ]; then
-    echo -e "Unable to install Hive: You should specify HIVE_DOWNLOAD_URL or HIVE_VERSION.\nAborting"
-    exit 1
-  fi
+    version_check=$(echo $HIVE_VERSION | sed -e '/[0-9]\.[0-9][0-9]\.[0-9]/d')
+    if [ ! -z $version_check ]; then
+        echo -e "Unable to install Hive: You should specify HIVE_DOWNLOAD_URL or HIVE_VERSION.\nAborting"
+        exit 1
+    fi
 fi
diff --git a/elements/java/install.d/33-java b/elements/java/install.d/33-java
--- a/elements/java/install.d/33-java
+++ b/elements/java/install.d/33-java
@@ -12,61 +12,61 @@ JAVA_HOME=$TARGET_ROOT$JAVA_TARGET_LOCATION
 mkdir -p $JAVA_HOME
 
 if [ -n "$JAVA_DOWNLOAD_URL" ]; then
-   install-packages wget
-   JAVA_FILE=$(basename $JAVA_DOWNLOAD_URL)
-   wget --no-check-certificate --no-cookies -c \
-       --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
-       -O $JAVA_HOME/$JAVA_FILE $JAVA_DOWNLOAD_URL
-   if [ $? -eq 0 ]; then
-      echo "Java download successful"
-   else
-      echo "Error downloading $JAVA_DOWNLOAD_URL, exiting"
-      exit 1
-   fi
+    install-packages wget
+    JAVA_FILE=$(basename $JAVA_DOWNLOAD_URL)
+    wget --no-check-certificate --no-cookies -c \
+        --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
+        -O $JAVA_HOME/$JAVA_FILE $JAVA_DOWNLOAD_URL
+    if [ $? -eq 0 ]; then
+        echo "Java download successful"
+    else
+        echo "Error downloading $JAVA_DOWNLOAD_URL, exiting"
+        exit 1
+    fi
 elif [ -n "$JAVA_FILE" ]; then
-   install -D -g root -o root -m 0755 $(dirname $0)/$JAVA_FILE $JAVA_HOME
+    install -D -g root -o root -m 0755 $(dirname $0)/$JAVA_FILE $JAVA_HOME
 fi
 
 if [ -z "$JAVA_FILE" ]; then
-   install-packages default-jre
+    install-packages default-jre
 else
-   cd $JAVA_HOME
-   if [[ $JAVA_FILE == *.tar.gz ]]; then
-      echo "Decompressing Java archive"
-      echo -e "\n" | tar -zxf $JAVA_FILE
-      JAVA_NAME=`ls -1 $JAVA_TARGET_LOCATION | grep -v tar.gz`
-      echo "Setting up $JAVA_NAME"
-      chown -R root:root $JAVA_HOME
-      cat >> /etc/profile.d/java.sh <<EOF
+    cd $JAVA_HOME
+    if [[ $JAVA_FILE == *.tar.gz ]]; then
+        echo "Decompressing Java archive"
+        echo -e "\n" | tar -zxf $JAVA_FILE
+        JAVA_NAME=`ls -1 $JAVA_TARGET_LOCATION | grep -v tar.gz`
+        echo "Setting up $JAVA_NAME"
+        chown -R root:root $JAVA_HOME
+        cat >> /etc/profile.d/java.sh <<EOF
 # Custom Java install
 export JAVA_HOME=$JAVA_TARGET_LOCATION/$JAVA_NAME
 export PATH=\$PATH:$JAVA_TARGET_LOCATION/$JAVA_NAME/bin
 EOF
-      case "$distro" in
-         Ubuntu )
-            echo "Setting up alternatives for Java"
-            update-alternatives --install "/usr/bin/java" "java" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java" 1
-            update-alternatives --install "/usr/bin/javac" "javac" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac" 1
-            update-alternatives --install "/usr/bin/javaws" "javaws" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws" 1
+        case "$distro" in
+            Ubuntu )
+                echo "Setting up alternatives for Java"
+                update-alternatives --install "/usr/bin/java" "java" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java" 1
+                update-alternatives --install "/usr/bin/javac" "javac" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac" 1
+                update-alternatives --install "/usr/bin/javaws" "javaws" "$JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws" 1
 
-            update-alternatives --set java $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java
-            update-alternatives --set javac $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac
-            update-alternatives --set javaws $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws
-         ;;
-         Fedora | RedHatEnterpriseServer | CentOS )
-            alternatives --install /usr/bin/java java $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java 200000
-            alternatives --install /usr/bin/javaws javaws $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws 200000
-            alternatives --install /usr/bin/javac javac $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac 200000
-            alternatives --install /usr/bin/jar jar $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/jar 200000
-         ;;
-      esac
-   elif [[ $JAVA_FILE == *.bin ]]; then
-      echo -e "\n" | sh $JAVA_FILE
-   else
-      echo "Unknown file type: $JAVA_FILE, exiting"
-      exit 1
-   fi
-   rm $JAVA_FILE
+                update-alternatives --set java $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java
+                update-alternatives --set javac $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac
+                update-alternatives --set javaws $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws
+            ;;
+            Fedora | RedHatEnterpriseServer | CentOS )
+                alternatives --install /usr/bin/java java $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/java 200000
+                alternatives --install /usr/bin/javaws javaws $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javaws 200000
+                alternatives --install /usr/bin/javac javac $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/javac 200000
+                alternatives --install /usr/bin/jar jar $JAVA_TARGET_LOCATION/$JAVA_NAME/bin/jar 200000
+            ;;
+        esac
+    elif [[ $JAVA_FILE == *.bin ]]; then
+        echo -e "\n" | sh $JAVA_FILE
+    else
+        echo "Unknown file type: $JAVA_FILE, exiting"
+        exit 1
+    fi
+    rm $JAVA_FILE
 fi
 
 echo "End: installation of Java"
diff --git a/elements/root-passwd/post-install.d/99-setup b/elements/root-passwd/post-install.d/99-setup
--- a/elements/root-passwd/post-install.d/99-setup
+++ b/elements/root-passwd/post-install.d/99-setup
@@ -1,7 +1,7 @@
 #!/bin/bash
 if [ -z "$DIB_PASSWORD" ]; then
-   echo "Error during setup password for root"
-   exit 1
+    echo "Error during setup password for root"
+    exit 1
 fi
 sed -i "s/disable_root: true/disable_root: false/" /etc/cloud/cloud.cfg
 install-packages augeas-tools openssh-server openssh-client
diff --git a/elements/spark/install.d/60-spark b/elements/spark/install.d/60-spark
--- a/elements/spark/install.d/60-spark
+++ b/elements/spark/install.d/60-spark
@@ -10,29 +10,29 @@ pushd $tmp_dir
 
 # The user is not providing his own Spark distribution package
 if [ -z "$SPARK_DOWNLOAD_URL" ]; then
-  # Check hadoop version
-  # INFO on hadoop versions: http://spark.apache.org/docs/latest/hadoop-third-party-distributions.html
-  if [ -z "$DIB_SPARK_VERSION" ]; then
-    case "$DIB_HADOOP_VERSION" in
-      CDH4)
-        DIB_SPARK_VERSION=1.0.0
-        SPARK_HADOOP_DL=cdh4
-        ;;
-      *)
-        echo -e "WARNING: Hadoop version $DIB_HADOOP_VERSION not supported."
-        echo -e "WARNING: make sure SPARK_DOWNLOAD_URL points to a compatible Spark version."
-        ;;
-    esac
-  fi
+    # Check hadoop version
+    # INFO on hadoop versions: http://spark.apache.org/docs/latest/hadoop-third-party-distributions.html
+    if [ -z "$DIB_SPARK_VERSION" ]; then
+        case "$DIB_HADOOP_VERSION" in
+            CDH4)
+                DIB_SPARK_VERSION=1.0.0
+                SPARK_HADOOP_DL=cdh4
+                ;;
+            *)
+                echo -e "WARNING: Hadoop version $DIB_HADOOP_VERSION not supported."
+                echo -e "WARNING: make sure SPARK_DOWNLOAD_URL points to a compatible Spark version."
+                ;;
+        esac
+    fi
 
-  SPARK_DOWNLOAD_URL="http://archive.apache.org/dist/spark/spark-$DIB_SPARK_VERSION/spark-$DIB_SPARK_VERSION-bin-$SPARK_HADOOP_DL.tgz"
+    SPARK_DOWNLOAD_URL="http://archive.apache.org/dist/spark/spark-$DIB_SPARK_VERSION/spark-$DIB_SPARK_VERSION-bin-$SPARK_HADOOP_DL.tgz"
 fi
 
 echo "Downloading SPARK"
 wget "$SPARK_DOWNLOAD_URL"
 if [ $? -ne 0 ]; then
-   echo -e "Could not download spark.\nAborting"
-   exit 1
+    echo -e "Could not download spark.\nAborting"
+    exit 1
 fi
 
 echo "Extracting SPARK"
diff --git a/elements/storm/root.d/0-check b/elements/storm/root.d/0-check
--- a/elements/storm/root.d/0-check
+++ b/elements/storm/root.d/0-check
@@ -1,5 +1,5 @@
 #!/bin/bash
 if [ -z "$STORM_DOWNLOAD_URL" -a -z "$DIB_STORM_VERSION"]; then
-  echo -e "Neither DIB_STORM_VERSION nor STORM_DOWNLOAD_URL are set. Impossible to install Storm.\nAborting"
-  exit 1
+    echo -e "Neither DIB_STORM_VERSION nor STORM_DOWNLOAD_URL are set. Impossible to install Storm.\nAborting"
+    exit 1
 fi
diff --git a/elements/swift_hadoop/post-install.d/81-add-jar b/elements/swift_hadoop/post-install.d/81-add-jar
--- a/elements/swift_hadoop/post-install.d/81-add-jar
+++ b/elements/swift_hadoop/post-install.d/81-add-jar
@@ -6,14 +6,14 @@ HDFS_LIB_DIR="/usr/share/hadoop/lib"
 SWIFT_LIB_URI="http://sahara-files.mirantis.com/hadoop-swift/hadoop-swift-latest.jar"
 
 if [ -z "$swift_url" ]; then
-   wget -O $HDFS_LIB_DIR/hadoop-swift.jar $SWIFT_LIB_URI
+    wget -O $HDFS_LIB_DIR/hadoop-swift.jar $SWIFT_LIB_URI
 else
-   wget -O $HDFS_LIB_DIR/hadoop-swift.jar $swift_url
+    wget -O $HDFS_LIB_DIR/hadoop-swift.jar $swift_url
 fi
 
 if [ $? -ne 0 ]; then
-   echo -e "Could not download Swift Hadoop FS implementation.\nAborting"
-   exit 1
+    echo -e "Could not download Swift Hadoop FS implementation.\nAborting"
+    exit 1
 fi
 
 chmod 0644 $HDFS_LIB_DIR/hadoop-swift.jar
