Add support building images for Hadoop 2.4.0
partially implements blueprint add-vanilla-2-hadoop-2-4-0

Change-Id: I0b534f37dcb589545070d3db670bf3d21471b67d

diff --git a/elements/oozie/root.d/0-check b/elements/oozie/root.d/0-check
--- a/elements/oozie/root.d/0-check
+++ b/elements/oozie/root.d/0-check
@@ -6,9 +6,17 @@ if [[ "$DIB_HADOOP_VERSION" < "2.0.0" ]]; then
         echo "OOZIE_HADOOP_V1_FILE and OOZIE_HADOOP_V1_DOWNLOAD_URL are not set. Impossible to install Oozie. Exit"
         exit 1
     fi
-else
-    if [ -z "$OOZIE_HADOOP_V2_DOWNLOAD_URL" -a -z "$OOZIE_HADOOP_V2_FILE" ]; then
-        echo "OOZIE_HADOOP_V2_FILE and OOZIE_HADOOP_V2_DOWNLOAD_URL are not set. Impossible to install Oozie. Exit"
+elif [ "$DIB_HADOOP_VERSION" == "2.3.0" ]; then
+    if [ -z "$OOZIE_HADOOP_V2_3_DOWNLOAD_URL" -a -z "$OOZIE_HADOOP_V2_3_FILE" ]; then
+        echo "OOZIE_HADOOP_V2_3_FILE and OOZIE_HADOOP_V2_3_DOWNLOAD_URL are not set. Impossible to install Oozie. Exit"
         exit 1
     fi
+elif [ "$DIB_HADOOP_VERSION" == "2.4.0" ]; then
+    if [ -z "$OOZIE_HADOOP_V2_4_DOWNLOAD_URL" -a -z "$OOZIE_HADOOP_V2_4_FILE" ]; then
+        echo "OOZIE_HADOOP_V2_4_FILE and OOZIE_HADOOP_V2_4_DOWNLOAD_URL are not set. Impossible to install Oozie. Exit"
+        exit 1
+    fi
+else
+    echo "Unknown Hadoop version selected. Aborting"
+    exit 1
 fi
